[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/n8n/*"
  to = "https://architecture-bones-parliamentary-wars.trycloudflare.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}