[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/n8n/*"
  to = "https://rendered-cloud-salon-mpeg.trycloudflare.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}